services:
  locrun-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: locrun-server
    env_file:
      - .env
    ports:
      - "${HTTPS_PORT:-443}:443"
      - "${SSH_PORT:-22}:22"
    restart: unless-stopped
